name: CI
on:
    push:
        tags-ignore: v*.*
        branches:
            - '*'
            - '*/*'
    pull_request:
        branches:
            - '*'
jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Init
              run: sudo apt update && sudo apt upgrade && sudo apt install xorg-dev ninja-build
            - name: Configure
              run: cmake --preset=nc-gsm-debug -S .
            - name: Build
              run: cmake --build build/db
